# SmarTSignalAI/docker/docker-compose.yml

version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./SmarTSignalAI:/app
    environment:
      - PYTHONUNBUFFERED=1
