# .github/workflows/ci-cd.yml

name: CI Pipeline

on: [push, pull_request]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r SmarTSignalAI/requirements.txt

      - name: Run unit tests
        run: |
          pytest SmarTSignalAI/tests/unit
